name: zee5_checker_bot
description: "A Zee5 Checker Bot Made In Pure Dart Native."
version: "1.0.0"
homepage: "https://github.com/BLUE-DEVIL1134/Zee5DartChecker/"

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  path: ^1.8.0
  teledart: ^0.2.1
  http: ^0.13.4

dev_dependencies:
  pedantic: ^1.9.2
